config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.views import defaults as default_views
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
  # Django Admin, use {% url 'admin:index' %}
  path(settings.ADMIN_URL, admin.site.urls),
  # User management
  path("users/", include("mtgcube.users.urls", namespace="users")),
  path("accounts/", include("allauth.urls")),
  re_path(r"^terms/", include("termsandconditions.urls")),
  # Your stuff: custom urls includes go here
  path("", include("tournaments.urls")),
  path("jsi18n/", JavaScriptCatalog.as_view(), name="javascript-catalog"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
  # This allows the error pages to be debugged during development, just visit
  # these url in browser to see how these error pages look like.
  urlpatterns += [
    path(
      "400/",
      default_views.bad_request,
      kwargs={"exception": Exception("Bad Request!")},
    ),
    path(
      "403/",
      default_views.permission_denied,
      kwargs={"exception": Exception("Permission Denied")},
    ),
    path(
      "404/",
      default_views.page_not_found,
      kwargs={"exception": Exception("Page not Found")},
    ),
    path("500/", default_views.server_error),
  ]
  if "debug_toolbar" in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

mtgcube/tournaments/urls.py
from django.urls import path

from .views import admin_data_views as admin
from .views import player_data_views as player
from .views import generic_data_views as generic
from .views import template_views as templates

app_name = "tournaments"

urlpatterns = [
  path("", templates.MyEventsView.as_view(), name="index"),
  path("registration/", templates.AvailableEvents.as_view(), name="available_events"),
  path("cube/<slug:slug>/", templates.CubeDetailView.as_view(), name="cube_detail"),
  path(
    "event-dashboard/<slug:slug>/",
    templates.EventDashboardView.as_view(),
    name="event_dashboard",
  ),
  path(
    "admin-dashboard/<slug:slug>/",
    templates.AdminDashboardView.as_view(),
    name="admin_dashboard",
  ),
  path(
    "admin-dashboard/<slug:slug>/player-list/",
    templates.AdminPlayerListView.as_view(),
    name="admin_player_list",
  ),
  path(
    "admin-dashboard/<slug:slug>/<slug:draft_slug>/",
    templates.AdminDraftDashboardView.as_view(),
    name="admin_draft_dashboard",
  ),
  path(
    "admin-dashboard/<slug:slug>/<slug:draft_slug>/~draft/",
    admin.AdminDraftInfoEmbedView.as_view(),
    name="admin_draft_embed",
  ),
  path(
    "admin-dashboard/<slug:slug>/~match/<int:match_id>/",
    admin.AdminMatchInfoEmbedView.as_view(),
    name="admin_match_embed",
  ),
  path(
    "event-dashboard/<slug:slug>/<slug:draft_slug>/",
    templates.DraftDashboardView.as_view(),
    name="draft_dashboard",
  ),
  path(
    "event-dashboard/<slug:slug>/<slug:draft_slug>/checkin-upload/",
    player.CheckinView.as_view(),
    name="checkin",
  ),
  path(
    "event-dashboard/<slug:slug>/<slug:draft_slug>/checkout-upload/",
    player.CheckoutView.as_view(),
    name="checkout",
  ),
  path(
    "event-dashboard/<slug:slug>/<slug:draft_slug>/checkin-pool/",
    templates.MyPoolCheckinView.as_view(),
    name="my_pool_checkin",
  ),
  path(
    "event-dashboard/<slug:slug>/<slug:draft_slug>/checkout-pool/",
    templates.MyPoolCheckoutView.as_view(),
    name="my_pool_checkout",
  ),
  path(
    "event-dashboard/<slug:slug>/<slug:draft_slug>/<int:image_id>/~checkindelete/",
    player.DeleteImageCheckinView.as_view(),
    name="delete_image_checkin",
  ),
  path(
    "event-dashboard/<slug:slug>/<slug:draft_slug>/<int:image_id>/~checkoutdelete/",
    player.DeleteImageCheckoutView.as_view(),
    name="delete_image_checkout",
  ),
  path(
    "event-dashboard/<slug:slug>/<slug:draft_slug>/~player-draft-info/",
    player.PlayerDraftInfoView.as_view(),
    name="player_draft_info",
  ),
  path(
    "event-dashboard/<slug:slug>/<slug:draft_slug>/~player-basic-info/",
    player.PlayerBasicInfoView.as_view(),
    name="player_basic_info",
  ),
  path(
    "event-dashboard/<slug:slug>/<slug:draft_slug>/<int:match_id>/~player-match/",
    player.PlayerFullMatchInfoView.as_view(),
    name="player_match_info",
  ),
  path(
    "event-dashboard/<slug:slug>/<slug:draft_slug>/~player-pairings/",
    player.PlayerOtherPairingsInfoView.as_view(),
    name="player_pairings_info",
  ),
  path(
    "event-dashboard/<slug:slug>/<slug:draft_slug>/~draft-standings/",
    generic.DraftStandingsView.as_view(),
    name="draft_standings",
  ),
  path(
    "event-dashboard/<slug:slug>/<slug:draft_slug>/~seatings/",
    generic.SeatingsView.as_view(),
    name="seatings",
  ),
  path(
    "event-dashboard/<slug:slug>/<slug:draft_slug>/~players/",
    generic.PlayerListView.as_view(),
    name="draft_players",
  ),
  path(
    "event-dashboard/<slug:slug>/<slug:draft_slug>/~player-match-preview/",
    player.PlayerPreviewMatchInfoView.as_view(),
    name="player_match_info_light",
  ),
  path(
    "event-dashboard/<slug:slug>/~timetable/",
    player.TimetableView.as_view(),
    name="timetable",
  ),
  path(
    "event-dashboard/<slug:slug>/~standings/",
    generic.EventStandingsView.as_view(),
    name="event_standings",
  ),
  path(
    "event-dashboard/<slug:slug>/~announcement/",
    player.AnnouncementView.as_view(),
    name="announcement",
  ),
]

mtgcube/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

from django.views.generic import TemplateView

urlpatterns = [
  path("admin/", admin.site.urls),
  path("account/", include("allauth.urls")),
  path("", TemplateView.as_view(template_name="base.html")),
  re_path(r"^mtgcube/", include("mtgcube.urls")),
]

mtgcube/users/urls.py
from django.urls import path

from mtgcube.users.views import (
  user_detail_view,
  user_redirect_view,
  user_update_view,
  google_login,
)

app_name = "users"
urlpatterns = [
  path("~redirect/", view=user_redirect_view, name="redirect"),
  path("~update/", view=user_update_view, name="update"),
  path("<str:username>/", view=user_detail_view, name="detail"),
  path("google-login", view=google_login, name="google-login"),
]

mtgcube/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
  """Default user."""

  #: First and last name do not cover name patterns around the globe
  name = CharField(_("Display Name"), default="", max_length=255)

  NEITHER = "n"
  MALE = "m"
  FEMALE = "f"
  NONBINARY = "x"

  PRONOUN_CHOICES = {
    NEITHER: _("neither/don't want to say"),
    MALE: _("he/him"),
    FEMALE: _("she/her"),
    NONBINARY: _("they/them"),
  }

  pronouns = CharField(
    "My Pronouns", max_length=1, choices=PRONOUN_CHOICES, default=NEITHER
  )

  first_name = None  # type: ignore
  last_name = None  # type: ignore

  def get_absolute_url(self):
    """Get url for user's detail view.

    Returns:
        str: URL for user detail.

    """
    return reverse("users:detail", kwargs={"username": self.username})

  def save(self, *args, **kwargs):
    """Override the original save method to set the name."""
    super(User, self).save(*args, **kwargs)

    if self.name == "":
      self.name = self.username
      self.save()

mtgcube/tournaments/forms.py
from django import forms
from .models import Image

from django.utils.translation import gettext_lazy as _


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        label = _("Image")
        fields = ["image"]

    image = forms.ImageField()


class ReportResultForm(forms.Form):
    match_id = forms.CharField(widget=forms.HiddenInput())
    player1_wins = forms.ChoiceField(choices=[(i, str(i)) for i in range(3)])
    player2_wins = forms.ChoiceField(choices=[(i, str(i)) for i in range(3)])

    def clean(self):
        cleaned_data = super().clean()
        p1w = cleaned_data.get("player1_wins")
        p2w = cleaned_data.get("player2_wins")

        if int(p1w) + int(p2w) > 3:
            raise forms.ValidationError(_("Total wins cannot be greater than 3."))


class ConfirmResultForm(forms.Form):
    confirm_match_id = forms.CharField(widget=forms.HiddenInput())

mtgcube/tournaments/views/admin_data_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.views import View

from .. import queries


class AdminDraftInfoEmbedView(LoginRequiredMixin, View):
  def get(self, request, *args, **kwargs):
    user = request.user
    if not user.is_superuser:
      return JsonResponse({"error": "Missing authentication level"}, status=403)

    draft = queries.get_draft(slug=kwargs["draft_slug"])

    players = [enrollment.player.user.name for enrollment in draft.enrollments.all()]

    current_round = queries.current_round(draft, force_update=True)
    matches = None
    if current_round:
      matches = queries.matches_from_draft(draft, current_round)

    # Check if there are matches in progress
    in_progress = False
    if matches:
      for match in matches:
        if not match.result_confirmed:
          in_progress = True
          break

    draft_finished = False

    if not current_round:
      paired = False
      rd_finished = False
      rd_idx = 0
    else:
      rd_finished = current_round.finished
      if rd_finished and current_round.round_idx == draft.round_number:
        draft_finished = True
      paired = current_round.paired
      rd_idx = current_round.round_idx

    return JsonResponse(
      {
        "cube": draft.cube.name,
        "cube_url": draft.cube.url,
        "players": players,
        "seated": draft.seated,
        "started": draft.started,
        "finished": rd_finished,
        "paired": paired,
        "in_progress": in_progress,
        "draft_round": rd_idx,
        "event_round": draft.phase.tournament.current_round,
        "draft_finished": draft_finished,
      }
    )


class AdminMatchInfoEmbedView(LoginRequiredMixin, View):
  def get(self, request, *args, **kwargs):
    user = request.user
    if not user.is_superuser:
      return JsonResponse({"error": "Missing authentication level"}, status=403)

    match_id = self.kwargs["match_id"]

    match = queries.get_match(match_id)

    return JsonResponse(
      {
        "table": match.table,
        "player1": match.player1.player.user.name,
        "player2": match.player2.player.user.name,
        "player1_wins": match.player1_wins,
        "player2_wins": match.player2_wins,
        "result": match.game_result_formatted(),
        "result_confirmed": match.result_confirmed,
        "reported_by": match.result_reported_by,
      }
    )

mtgcube/tournaments/views/generic_data_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.views import View

from .. import queries


class SeatingsView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        draft = queries.get_draft(slug=kwargs["draft_slug"])

        if not draft:
            return JsonResponse({"error": "No draft found."}, status=404)

        if not draft.seated:
            return JsonResponse({"error": "No seatings yet."}, status=200)

        current_round = queries.current_round(draft)

        # Get seatings
        if current_round:
            if (
                current_round.started
                or current_round.paired
                or current_round.round_idx > 1
            ):
                return JsonResponse({"error": "No seatings anymore."})

        sorted_players = list(draft.enrollments.all().order_by("seat"))
        seatings_out = [
            {
                "seat": player.seat,
                "id": player.id,
                "name": player.player.user.name,
            }
            for player in sorted_players
        ]
        return JsonResponse({"seatings": seatings_out})


class PlayerListView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        draft = queries.get_draft(slug=kwargs["draft_slug"])

        if not draft:
            return JsonResponse({"error": "No draft found."}, status=404)

        players = [
            enrollment.player.user.name
            for enrollment in draft.enrollments.filter(dropped=False)
        ]

        return JsonResponse({"players": players})


class DraftStandingsView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        draft = queries.get_draft(slug=kwargs["draft_slug"])

        # Get standings
        standings = queries.draft_standings(draft)
        if not standings:
            return JsonResponse({"error": "No draft standings yet."}, status=200)

        current_round = queries.current_round(draft, force_update=True)

        if not current_round:
            return JsonResponse({"error": "No current round found."}, status=404)

        if not current_round.finished:
            rd_idx = current_round.round_idx - 1
        else:
            rd_idx = current_round.round_idx

        return JsonResponse({"standings": standings, "current_round": rd_idx})


class EventStandingsView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        tournament = queries.get_tournament(slug=kwargs["slug"], force_update=True)

        if not tournament:
            return JsonResponse({"error": "No tournament found."}, status=404)

        standings = queries.tournament_standings(tournament)

        if not standings:
            return JsonResponse({"error": "No event standings yet."})

        return JsonResponse(
            {"standings": standings, "current_round": tournament.current_round - 1}
        )

mtgcube/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView
from django.shortcuts import redirect
from django.views.decorators.csrf import csrf_exempt


User = get_user_model()


class IsCorrectUserMixin(LoginRequiredMixin):
    def test_func(self):
        return


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"

    def get(self, request, *args, **kwargs):
        user = request.user
        target_username = kwargs["username"]
        if user.username != target_username:
            messages.error(request, "You are not authorized to view this page.")
            return redirect("tournaments:index")

        return super().get(request, *args, **kwargs)


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name", "pronouns"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        self.request.user.save()
        return self.request.user.get_absolute_url()  # type: ignore [union-attr]

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("tournaments:index")


user_redirect_view = UserRedirectView.as_view()


@csrf_exempt
def google_login(request):
    from urllib.parse import urlparse

    url = urlparse(request.headers.get("Origin"))
    domain = url.hostname
    if url.port:
        domain += ":" + str(url.port)
    prefix = "https://" if request.is_secure() else "http://"
    home_page = prefix + domain if prefix not in domain else domain
    login_url = "/accounts/google/login/"
    return redirect(home_page + login_url)

mtgcube/templates/base.html
{% load i18n static static_version %}
<!DOCTYPE html>

{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}MtG Cube{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="icon" type="image/svg+xml" href="{% static 'favicon.svg' %}">
		<link rel="icon" type="image/png" href="{% static 'favicon.png' %}">
    <meta name="description" content="">

    {% block css %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% versioned_static 'css/vault-style.css' %}">
    {% endblock %}

  </head>

  <body class="vault-app darkmode">
    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'tournaments:index' %}">MtG Cube</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'tournaments:index' %}">{% trans "My events" %}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'tournaments:available_events' %}">{% trans "Sign up for an event" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>
    <main>

    {% if breadcrumbs %}
    <div class="breadcrumb-nav">
        {% include "dynamic_breadcrumbs/breadcrumbs.html" with breadcrumbs=breadcrumbs %}
    </div>
    {% endif %}

    <div class="container">

      {% if messages %}
        {% for message in messages %}
        <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
      {% endif %}

      {% block content %}
      {% endblock content %}

    </div>

    {% if not request.user.is_authenticated %}
      <div
        id="g_id_onload"
        data-client_id="914789792440-s3j2snqq4mjh24o0d6bdem01c87b98nl.apps.googleusercontent.com"
        data-login_uri="{% url 'users:google-login' %}"
        data-cancel_on_tap_outside="false">
      </div>
      <script src="https://accounts.google.com/gsi/client" async defer></script> <!-- NEW -->
    {% endif %}

    {% block modal %}{% endblock modal %}

    {% block javascript %}
      <!-- Bootstrap JS and its dependencies-->
      <script defer src="https://code.jquery.com/jquery-3.7.1.slim.js" integrity="sha256-UgvvN8vBkgO0luPSUl2s8TIlOSYRoGFAX4jlCIm9Adc=" crossorigin="anonymous"></script><script defer src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
      <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    {% endblock javascript %}

    {% block inline_javascript %}
    {# Script tags with only code, no src (defer by default) #}
    {% endblock inline_javascript %}
    </main>
  </body>
</html>
 

mtgcube/templates/terms_base.html
{% extends "base.html" %}