config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.views import defaults as default_views
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
  # Django Admin, use {% url 'admin:index' %}
  path(settings.ADMIN_URL, admin.site.urls),
  # User management
  path("users/", include("mtgcube.users.urls", namespace="users")),
  path("accounts/", include("allauth.urls")),
  re_path(r"^terms/", include("termsandconditions.urls")),
  # Your stuff: custom urls includes go here
  path("", include("tournaments.urls")),
  path("jsi18n/", JavaScriptCatalog.as_view(), name="javascript-catalog"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
  # This allows the error pages to be debugged during development, just visit
  # these url in browser to see how these error pages look like.
  urlpatterns += [
    path(
      "400/",
      default_views.bad_request,
      kwargs={"exception": Exception("Bad Request!")},
    ),
    path(
      "403/",
      default_views.permission_denied,
      kwargs={"exception": Exception("Permission Denied")},
    ),
    path(
      "404/",
      default_views.page_not_found,
      kwargs={"exception": Exception("Page not Found")},
    ),
    path("500/", default_views.server_error),
  ]
  if "debug_toolbar" in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

mtgcube/tournaments/urls.py
from django.urls import path

from .views import admin_data_views as admin
from .views import player_data_views as player
from .views import generic_data_views as generic
from .views import template_views as templates

app_name = "tournaments"

urlpatterns = [
  path("", templates.MyEventsView.as_view(), name="index"),
  path("registration/", templates.AvailableEvents.as_view(), name="available_events"),
  path("cube/<slug:slug>/", templates.CubeDetailView.as_view(), name="cube_detail"),
  path(
    "event-dashboard/<slug:slug>/",
    templates.EventDashboardView.as_view(),
    name="event_dashboard",
  ),
  path(
    "admin-dashboard/<slug:slug>/",
    templates.AdminDashboardView.as_view(),
    name="admin_dashboard",
  ),
  path(
    "admin-dashboard/<slug:slug>/player-list/",
    templates.AdminPlayerListView.as_view(),
    name="admin_player_list",
  ),
  path(
    "admin-dashboard/<slug:slug>/<slug:draft_slug>/",
    templates.AdminDraftDashboardView.as_view(),
    name="admin_draft_dashboard",
  ),
  path(
    "admin-dashboard/<slug:slug>/<slug:draft_slug>/~draft/",
    admin.AdminDraftInfoEmbedView.as_view(),
    name="admin_draft_embed",
  ),
  path(
    "admin-dashboard/<slug:slug>/~match/<int:match_id>/",
    admin.AdminMatchInfoEmbedView.as_view(),
    name="admin_match_embed",
  ),
  path(
    "event-dashboard/<slug:slug>/<slug:draft_slug>/",
    templates.DraftDashboardView.as_view(),
    name="draft_dashboard",
  ),
  path(
    "event-dashboard/<slug:slug>/<slug:draft_slug>/checkin-upload/",
    player.CheckinView.as_view(),
    name="checkin",
  ),
  path(
    "event-dashboard/<slug:slug>/<slug:draft_slug>/checkout-upload/",
    player.CheckoutView.as_view(),
    name="checkout",
  ),
  path(
    "event-dashboard/<slug:slug>/<slug:draft_slug>/checkin-pool/",
    templates.MyPoolCheckinView.as_view(),
    name="my_pool_checkin",
  ),
  path(
    "event-dashboard/<slug:slug>/<slug:draft_slug>/checkout-pool/",
    templates.MyPoolCheckoutView.as_view(),
    name="my_pool_checkout",
  ),
  path(
    "event-dashboard/<slug:slug>/<slug:draft_slug>/<int:image_id>/~checkindelete/",
    player.DeleteImageCheckinView.as_view(),
    name="delete_image_checkin",
  ),
  path(
    "event-dashboard/<slug:slug>/<slug:draft_slug>/<int:image_id>/~checkoutdelete/",
    player.DeleteImageCheckoutView.as_view(),
    name="delete_image_checkout",
  ),
  path(
    "event-dashboard/<slug:slug>/<slug:draft_slug>/~player-draft-info/",
    player.PlayerDraftInfoView.as_view(),
    name="player_draft_info",
  ),
  path(
    "event-dashboard/<slug:slug>/<slug:draft_slug>/~player-basic-info/",
    player.PlayerBasicInfoView.as_view(),
    name="player_basic_info",
  ),
  path(
    "event-dashboard/<slug:slug>/<slug:draft_slug>/<int:match_id>/~player-match/",
    player.PlayerFullMatchInfoView.as_view(),
    name="player_match_info",
  ),
  path(
    "event-dashboard/<slug:slug>/<slug:draft_slug>/~player-pairings/",
    player.PlayerOtherPairingsInfoView.as_view(),
    name="player_pairings_info",
  ),
  path(
    "event-dashboard/<slug:slug>/<slug:draft_slug>/~draft-standings/",
    generic.DraftStandingsView.as_view(),
    name="draft_standings",
  ),
  path(
    "event-dashboard/<slug:slug>/<slug:draft_slug>/~seatings/",
    generic.SeatingsView.as_view(),
    name="seatings",
  ),
  path(
    "event-dashboard/<slug:slug>/<slug:draft_slug>/~players/",
    generic.PlayerListView.as_view(),
    name="draft_players",
  ),
  path(
    "event-dashboard/<slug:slug>/<slug:draft_slug>/~player-match-preview/",
    player.PlayerPreviewMatchInfoView.as_view(),
    name="player_match_info_light",
  ),
  path(
    "event-dashboard/<slug:slug>/~timetable/",
    player.TimetableView.as_view(),
    name="timetable",
  ),
  path(
    "event-dashboard/<slug:slug>/~standings/",
    generic.EventStandingsView.as_view(),
    name="event_standings",
  ),
  path(
    "event-dashboard/<slug:slug>/~announcement/",
    player.AnnouncementView.as_view(),
    name="announcement",
  ),
]

mtgcube/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

from django.views.generic import TemplateView

urlpatterns = [
  path("admin/", admin.site.urls),
  path("account/", include("allauth.urls")),
  path("", TemplateView.as_view(template_name="base.html")),
  re_path(r"^mtgcube/", include("mtgcube.urls")),
]

mtgcube/users/urls.py
from django.urls import path

from mtgcube.users.views import (
  user_detail_view,
  user_redirect_view,
  user_update_view,
  google_login,
)

app_name = "users"
urlpatterns = [
  path("~redirect/", view=user_redirect_view, name="redirect"),
  path("~update/", view=user_update_view, name="update"),
  path("<str:username>/", view=user_detail_view, name="detail"),
  path("google-login", view=google_login, name="google-login"),
]

mtgcube/tournaments/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.utils import timezone
from mtgcube.users.models import User
from django.utils.translation import gettext_lazy as _
from django.urls import reverse

import datetime


class Tournament(models.Model):
    id = models.AutoField(primary_key=True)
    public = models.BooleanField(default=False)
    name = models.CharField(max_length=50, unique=True)
    start_datetime = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank=True)
    format_description = models.TextField(blank=True)
    player_capacity = models.IntegerField(default=0)
    signed_up = models.IntegerField(default=0)
    end_datetime = models.DateTimeField(default=timezone.now)
    location = models.CharField(max_length=255, blank=True)
    announcement = models.TextField(blank=True)
    slug = models.SlugField(unique=True)
    current_round = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

    @classmethod
    def get_default_pk(cls):
        tournament, __ = cls.objects.get_or_create(name="Cube Open Hamburg 2024")
        return tournament.pk


class SideEvent(Tournament):
    tournament = models.ForeignKey(
        Tournament, related_name="side_events", on_delete=models.CASCADE
    )


class Phase(models.Model):
    id = models.AutoField(primary_key=True)
    tournament = models.ForeignKey("Tournament", on_delete=models.CASCADE)
    phase_idx = models.IntegerField("Phase Number", default=1)
    round_number = models.IntegerField("Amount of rounds", default=3)
    started = models.BooleanField(default=False)
    finished = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if self.phase_idx == 1:
            self.started = True
        super(Phase, self).save(*args, **kwargs)

    class Meta:
        unique_together = ["tournament", "phase_idx"]

    def __str__(self):
        return f"{self.tournament.name} - Phase {self.phase_idx}"


class Draft(models.Model):
    id = models.AutoField(primary_key=True)
    phase = models.ForeignKey("Phase", on_delete=models.CASCADE)
    cube = models.ForeignKey("Cube", on_delete=models.CASCADE)
    enrollments = models.ManyToManyField("Enrollment")
    round_number = models.IntegerField("Amount of rounds", default=3)
    first_table = models.IntegerField(default=0)
    last_table = models.IntegerField(default=0)
    started = models.BooleanField(default=False)
    finished = models.BooleanField(default=False)
    seated = models.BooleanField(default=False)
    slug = models.SlugField(unique=True)

    class Meta:
        unique_together = ["phase", "cube"]

    def __str__(self):
        return str(self.slug)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(
                f"{self.phase.tournament.name}{self.phase.phase_idx}{self.cube.name}"
            )
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("tournaments:admin_draft_dashboard", kwargs={"slug": self.slug})


class Round(models.Model):
    id = models.AutoField(primary_key=True)
    draft = models.ForeignKey("Draft", on_delete=models.CASCADE)
    round_idx = models.IntegerField("Round number", default=1)
    paired = models.BooleanField(default=False)
    started = models.BooleanField(default=False)
    finished = models.BooleanField(default=False)

    class Meta:
        unique_together = ["draft", "round_idx"]

    def __str__(self):
        return f"{self.draft} - Round {self.round_idx}"


class Player(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, default="")

    def __str__(self):
        return self.user.name


class Enrollment(models.Model):
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE)
    dropped = models.BooleanField(default=False)
    enrolled_on = models.DateTimeField(auto_now_add=True)
    registration_finished = models.BooleanField(default=False)
    score = models.IntegerField(default=0)
    games_played = models.IntegerField(default=0)
    games_won = models.IntegerField(default=0)
    pmw = models.FloatField(default=0)
    omw = models.FloatField(default=0)
    pgw = models.FloatField(default=0)
    ogw = models.FloatField(default=0)
    draft_score = models.IntegerField(default=0)
    draft_games_played = models.IntegerField(default=0)
    draft_games_won = models.IntegerField(default=0)
    draft_pmw = models.FloatField(default=0)
    draft_omw = models.FloatField(default=0)
    draft_pgw = models.FloatField(default=0)
    draft_ogw = models.FloatField(default=0)
    draft_place = models.PositiveIntegerField(default=0)
    tournament_place = models.PositiveIntegerField(default=0)
    checked_in = models.BooleanField(default=False)
    checked_out = models.BooleanField(default=False)
    pairings = models.ManyToManyField("self", blank=True)
    seat = models.IntegerField(default=0)
    paired = models.BooleanField(default=False)
    had_bye = models.BooleanField(default=False)
    bye_this_round = models.BooleanField(default=False)
    judge_note = models.CharField(max_length=450, blank=True)

    class Meta:
        unique_together = ("player", "tournament")

    def __str__(self):
        return f"{self.player.user.name} in {self.tournament.name}"


class Game(models.Model):
    id = models.AutoField(primary_key=True)
    round = models.ForeignKey("Round", on_delete=models.CASCADE)
    table = models.IntegerField(default=0)
    player1 = models.ForeignKey(
        "Enrollment", related_name="player1", on_delete=models.CASCADE
    )
    player2 = models.ForeignKey(
        "Enrollment", related_name="player2", on_delete=models.CASCADE
    )
    player1_wins = models.IntegerField(default=0)
    player2_wins = models.IntegerField(default=0)
    result = models.CharField(max_length=200, blank=True, null=True)
    result_reported_by = models.CharField(max_length=255, blank=True, null=True)
    result_confirmed = models.BooleanField(default=False)

    def __str__(self):
        return f"Round {self.round.round_idx}, Table {self.table}: {self.player1.player.user.name} vs {self.player2.player.user.name}"

    def game_result_formatted(self):
        if not self.result:
            return "Pending"
        else:
            if not self.result_confirmed:
                trans = _("(awaiting confirmation)")
                return self.result + f" {trans}"
            trans = _("(confirmed)")
            return self.result + f" {trans}"

    def game_formatted(self):
        p1 = self.player1.player.user.name
        p1name = p1 if p1 else self.player1.player.user.name
        p2 = self.player2.player.user.name
        p2name = p2 if p2 else self.player2.player.user.name
        return f"Table {self.table}: {p1name} - {p2name}"


def cube_directory_path(instance, filename):
    return f"images/cube_thumbnails/{instance.name}_{filename}"


class Cube(models.Model):
    id = models.AutoField(primary_key=True)
    creator = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=200, unique=True)
    card_number = models.IntegerField(default=0)
    description = models.TextField(blank=True)
    special_rules = models.TextField(blank=True)
    url = models.URLField("URL", max_length=200, unique=True)
    image = models.ImageField(upload_to=cube_directory_path, blank=True)
    slug = models.SlugField(null=True)

    def __str__(self):
        return self.name


def user_directory_path(instance, filename: str):
    f_extension = filename.split(".")[-1]
    now = datetime.datetime.now()
    fname = f"{'checkin' if instance.checkin else 'checkout'}-{now.strftime('%H%M%S')}.{f_extension}"
    tstring = str(instance.draft.phase.tournament).replace(" ", "-")
    dstring = (
        f"phase-{instance.draft.phase.phase_idx}-{instance.draft.cube.name}".replace(
            " ", "-"
        )
    )
    return f"images/userupload/{tstring}/{instance.user.username}/{dstring}/{fname}".lower()


class Image(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    draft = models.ForeignKey("Draft", null=True, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=user_directory_path)
    draft_idx = models.IntegerField("Draft ID", default=0)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    checkin = models.BooleanField(default=True)

    def __str__(self):
        img_time_fstring = self.uploaded_at.time().strftime("%H:%M:%S")
        draft = str(self.draft) if self.draft else ""
        return f"{self.user} - {draft} - Draft ID {self.draft_idx} - {'Checkin' if self.checkin else 'Checkout'} - ({img_time_fstring})"

mtgcube/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView
from django.shortcuts import redirect
from django.views.decorators.csrf import csrf_exempt


User = get_user_model()


class IsCorrectUserMixin(LoginRequiredMixin):
    def test_func(self):
        return


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"

    def get(self, request, *args, **kwargs):
        user = request.user
        target_username = kwargs["username"]
        if user.username != target_username:
            messages.error(request, "You are not authorized to view this page.")
            return redirect("tournaments:index")

        return super().get(request, *args, **kwargs)


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name", "pronouns"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        self.request.user.save()
        return self.request.user.get_absolute_url()  # type: ignore [union-attr]

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("tournaments:index")


user_redirect_view = UserRedirectView.as_view()


@csrf_exempt
def google_login(request):
    from urllib.parse import urlparse

    url = urlparse(request.headers.get("Origin"))
    domain = url.hostname
    if url.port:
        domain += ":" + str(url.port)
    prefix = "https://" if request.is_secure() else "http://"
    home_page = prefix + domain if prefix not in domain else domain
    login_url = "/accounts/google/login/"
    return redirect(home_page + login_url)

mtgcube/templates/tournaments/admin_dashboard.html
{% extends "tournaments/base.html" %}
{% load i18n tournament_utils %}

{% block title %}Admin Tournament Dashboard{% endblock %}

{% block content %}
<h1>{{ tournament.name }} - Admin Event Overview</h1>
<ul class="tournament-admin">
    <h5><a href="{% url 'tournaments:admin_player_list' tournament.slug %}">Manage Players</a></h5>
    <li class="admin-draft-overview">
        <ul>
            {% for draft_id in draft_ids %}
                {% with slug=slugs|get_item:draft_id %}
                    {% include 'tournaments/admin_draft_embed.html' with slug=slug draft_id=draft_id tournament_slug=tournament.slug %}
                {% endwith %}
            {% endfor %}
        </ul>
    </li>
    {% include 'tournaments/event_standings_embed.html' with tournament_slug=tournament.slug %}
    <li class="start-phase">
        <form class="start-phase-form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <button type="submit" name="start-phase" value="{{ tournament.id }}" onclick="return confirm();">Finish all ongoing drafts and start the next phase</button>
        </form>
    </li>
    <li class="finish-event-rd">
        <form class="finish-event-round-form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <button type="submit" name="finish-event-round" value="{{ tournament.id }}" onclick="return confirm();">Finish event round</button>
        </form>
    </li>
    <li class="reset-event">
        <form class="reset-event-form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <button type="submit" name="reset-event" value="{{ tournament.id }}" onclick="return confirm();">Hard reset tournament</button>
        </form>
    </li>
</ul>
{% endblock %}

mtgcube/templates/tournaments/admin_tournament_players.html
{% extends "tournaments/base.html" %}

{% load i18n %}

{% block title %}Admin Tournament View - Players{% endblock %}

{% block content %}
<h1>Admin Tournament View - Players</h1>
<h5>Enrolled users:</h5>
<ul>
    {% for e in users.enrolled %}
        <li class="d-flex flex-row">
            {{ e.name }}
        </li>
    {% empty %}
        None
    {% endfor %}
</ul>
<h5>Other users:</h5>
<ul style="columns:3;">
    {% for e in users.not_enrolled %}
        {% if not e.is_superuser %}
            <li class="d-flex flex-row align-items-center mb-2">
                <span class="name-section" style="min-width: 150px;">{{ e.name }}</span>
                <form class="enroll-form d-inline-block ms-3" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <button class="btn btn-gray btn-sm" name="user-id" value="{{ e.id }}" type="submit" onclick="return confirm('Register {{e.username}}?');">
                        {% trans 'Register' %}
                    </button>
                </form>
            </li>
        {% endif %}
    {% empty %}
        None
    {% endfor %}
</ul>
{% endblock %}

mtgcube/templates/tournaments/checkin.html
{% extends "tournaments/base.html" %}
{% load static i18n %}
{% block title %}Check-in{% endblock %}
{% block javascript %}
    {{ block.super }}
    <script>
    document.getElementById('upload-form').addEventListener('submit', function() {
        document.getElementById('loading-gif').style.display = 'block';
    });
    </script>
{% endblock %}
{% block content %}
    <div class="check-in">
        <h1>{% trans 'Check-in: Deck image upload' %}</h1>
        <h5>
            {% trans 'For check-in, please upload at least one image with your entire deck and one with your entire pool. All cards need to be clearly visible.' %}
        </h5>
        <form id="upload-form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">{% trans 'Upload' %}</button>
        </form>
        <div id="loading-gif" style="display:none;">
            <p>{% trans 'Uploading, please wait' %}...</p>
            <img src="{% static 'loading.gif' %}" alt="Loading..." />
        </div>
    </div>
{% endblock %}

mtgcube/templates/tournaments/draft_standings_embed.html
{% load i18n static %}

{% block javascript %}
<script src="{% url 'javascript-catalog' %}"></script>
<script src="{% static 'js/draft_standings.js' %}"></script>
{% endblock %}

{% block content %}
<li class="standings" id="standings-container" data-tournament-slug="{{ tournament_slug }}" data-draft-slug="{{ draft.slug }}" style="display:none;">
    <h5 id="draft-standings-header"></h5>
    <p id="draft-standings-info"></p>
    <table class="standings-table" id="draft-standings">
        <thead>
            <tr>
                <th style="text-align: center; padding-right: 40px;">#</th>
                <th style="text-align: center; padding-right: 40px;">Name</th>
                <th style="text-align: center; padding-right: 40px;">Pts</th>
                <th style="text-align: center; padding-right: 40px;">OMW%</th>
                <th style="text-align: center; padding-right: 40px;">PGW%</th>
                <th style="text-align: center; padding-right: 40px;">OGW%</th>
            </tr>
            <tbody></tbody>
        </thead>
    </table>
</li>
{% endblock %}

mtgcube/templates/tournaments/event_dashboard.html
{% extends "tournaments/base.html" %}
{% load i18n static %}
{% block title%}My event dashboard{% endblock %}

{% block javascript %}
{{ block.super }}
<script src="{% url 'javascript-catalog' %}"></script>
<script src="{% static 'js/event_dashboard.js' %}"></script>
{% endblock %}

{% block content %}
<div class="event-dashboard" id="dashboard-container" data-tournament-slug="{{ tournament.slug }}" data-draft-slug="{{ draft.slug }}">
    <h4>{% trans 'Event Dashboard' %}</h4>
    <div class="event-title" id="event-info-header">
        <h1 class="event-name">{{ tournament.name }}</h1>
    </div>
    <div class="signup-status" id="player-signup-status"></div>
    <div class="event-announcement" id="announcement" style="display:none;"></div>
    <ul class="player-info-list">
        <li class="draft-info" id="draft-info-header"></li>
        <li class="cube-info" id="player-cube-info"></li>
        {% include 'tournaments/current_match_preview_embed.html' with tournament=tournament %}
        {% include 'tournaments/event_standings_embed.html' with tournament_slug=tournament.slug %}
        {% include 'tournaments/timetable_embed.html' with tournament_slug=tournament.slug %}
    </ul>
</div>
{% endblock %}

mtgcube/templates/tournaments/event_panel_embed.html
{% load i18n %}
{% load i18n tournament_filter %}

{% block content %}
    {% if tournament|is_side_event %}
        <li class="side-event-signup-panel">
    {% else %}
        <li class="main-event-signup-panel">
    {% endif %}
        <ul class="event-info">
            <li class="event-title"><h5>{{tournament.name}}</h5></li>
            <li class="event-description">{{tournament.description}}</li>
            <li class="event-capacity"><strong>{% trans 'Registrations' %}</strong>: {{ tournament.signed_up }}/{{ tournament.player_capacity }}</li>
            <li class="event-format"><strong>Format:</strong> {{ tournament.format_description|safe|linebreaksbr }}</li>
            <li class="event-time"><strong>{% trans 'Start' %}</strong>: {{ tournament.start_datetime }} - <strong>{% trans 'End' %}</strong>: {{tournament.end_datetime}}</li>
            {% if status %}
                <button class="registration-button already-registered" type="submit" disabled>{% trans 'You registration is complete' %}!</button>
            {% else %}
                <button class="registration-button registration-pending" type="submit" disabled>{% trans 'Your registration still needs to be confirmed by a tournament official' %}</button>
            {% endif %}
        </ul>
    </li>
{% endblock %}

mtgcube/templates/tournaments/event_standings_embed.html
{% load i18n static %}

{% block javascript %}
<script src="{% url 'javascript-catalog' %}"></script>
<script src="{% static 'js/event_standings.js' %}"></script>
{% endblock %}

{% block content %}
<li class="standings" id="standings-container" data-tournament-slug="{{ tournament_slug }}" style="display:none;">
    <h5 id="event-standings-header-{{ tournament_slug }}"></h5>
    <p id="event-standings-info-{{ tournament_slug }}"></p>
    <table class="standings-table" id="event-standings-{{ tournament_slug }}">
        <thead>
            <tr>
                <th style="text-align: center; padding-right: 40px;">#</th>
                <th style="text-align: center; padding-right: 40px;">Name</th>
                <th style="text-align: center; padding-right: 40px;">Pts</th>
                <th style="text-align: center; padding-right: 40px;">OMW%</th>
                <th style="text-align: center; padding-right: 40px;">PGW%</th>
                <th style="text-align: center; padding-right: 40px;">OGW%</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</li>
{% endblock %}

mtgcube/templates/tournaments/my_pool_checkin.html
{% extends "tournaments/base.html" %}
{% load i18n %}
{% block title%}{% trans 'My check-in pool & decklist submissions' %}{% endblock %}

{% block content %}
<div class="pool-info-checkin">
    <h1>
        {% trans 'My check-in pool & decklist submissions' %}
    </h1>
    <div class="upload-more">
        <a href="{% url 'tournaments:checkin' tournament.slug draft.slug %}">{% trans 'Upload deck images' %}</a>
    </div>
    <ul>
        {% for image in images %}
            <li>
                <img src="{{ image.image.url }}" alt="{{ image }}">
                <a href="{% url 'tournaments:delete_image_checkin' tournament.slug draft.slug image.id %}">{% trans 'Delete' %}</a>
            </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

mtgcube/templates/tournaments/pairings_embed.html
{% load i18n static %}

{% block javascript %}
<script src="{% url 'javascript-catalog' %}"></script>
<script src="{% static 'js/pairings.js' %}"></script>
{% endblock %}

{% block content %}
<li class="pairings-info" id="player-pairings" data-tournament-slug="{{ tournament_slug }}" data-draft-slug="{{ draft.slug }}">
    <h5 id="pairings-header"></h5>
    <ul class="pairings-list" id="pairings"></ul>
</li>
{% endblock %}

mtgcube/templates/tournaments/player_list_embed.html
{% load i18n static %}

{% block javascript %}
<script src="{% url 'javascript-catalog' %}"></script>
<script src="{% static 'js/player_list.js' %}"></script>
{% endblock %}

{% block content %}

<li class="player-list-embed" id="player-list" data-tournament-slug="{{ tournament_slug }}" data-draft-slug="{{ draft.slug }}">
    <h5>Players:</h5>
    <p id="player-list-inner"></p>
</li>
{% endblock %}